apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
      - name: catalog-service
        image: ghcr.io/zzzang12-cns/catalog-service
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command: [ "sh", "-c", "sleep 5" ]
        ports:
        - containerPort: 9001
        env:
        - name: BPL_JVM_THREAD_COUNT
          value: "50"
        - name: SPRING_CLOUD_CONFIG_URI
          value: config-service.default.svc.cluster.local
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://polar-postgres.default.svc.cluster.local/polardb_catalog
        - name: SPRING_PROFILES_ACTIVE
          value: testdata