FROM eclipse-temurin:17.0.11_9-jdk-jammy AS builder
WORKDIR /workspace
COPY gradlew .
COPY gradlew.bat .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY src src
RUN chmod +x gradlew
RUN ./gradlew bootJar

FROM eclipse-temurin:17.0.11_9-jre-jammy AS extractor
WORKDIR /workspace
ARG APPLICATION_FILE=catalog-service.jar
COPY --from=builder /workspace/build/libs/${APPLICATION_FILE} ${APPLICATION_FILE}
RUN java -Djarmode=tools -jar ${APPLICATION_FILE} extract --layers --launcher

FROM eclipse-temurin:17.0.11_9-jre-jammy AS runner
RUN useradd spring
USER spring
WORKDIR /workspace
ARG APPLICATION=catalog-service
COPY --from=extractor /workspace/${APPLICATION}/dependencies ./
COPY --from=extractor /workspace/${APPLICATION}/spring-boot-loader ./
COPY --from=extractor /workspace/${APPLICATION}/snapshot-dependencies ./
COPY --from=extractor /workspace/${APPLICATION}/application ./
CMD java org.springframework.boot.loader.JarLauncer
EXPOSE 8080
